### ISSUE TITLE
MultiQC: Custom Content

### ISSUE THREAD

**Issue by lecorguille** [EnginesOn/galaxy_tools#13]
Salut les EnginesOn and other,

As I proposed in this [thread](https://github.com/ewels/MultiQC/issues/535), I plan to add the support of the *Custom Content* within the Galaxy wrapper.
That way, users will be able to deal with "classic" "generic" 2 columns tables like this one:

```
"Retention Time"        "TIC"
2503.69308488001        44464
2505.25808488001        44632
2506.82308488001        45232
2508.38808488001        46200
2509.95308488001        46592
2511.51808488001        46376
2513.08308488001        45760
```

And that way, I will be able to include MultiQC as a tool within the W4M workflow to display TIC and BPC Mass Chromatogram. Hey!

If someone disapprove, he speaks now or forever hold your peace that! 🙊 

Schüss

**Comment by yvanlebras** [comment]
Vers Good idea ! Maybe the Best approach could be to propose adding these functionnality to the command MultiQC tool and then updating the Galaxy wrapper ? This can make sens for you ?

**Comment by lecorguille** [comment]
This is already implemented in MultiQC
I plan to propose 3 solutions for the Custom Content feature
- embedded setting in the file headers like in the thread so nonneed any inputs
- join a MultiQC yaml config file as input data
- fill a form with the title and the label axis

**Comment by lecorguille** [comment]
Done: https://github.com/EnginesOn/galaxy_tools/pull/14

**Comment by yvanlebras** [comment]
Thanks !
