### ISSUE TITLE
MultiQC outputing error

### ISSUE THREAD

**Issue by vebaev** [EnginesOn/galaxy_tools#17]
After successful installation on MultiQC on Galaxy v17.09 it outputs error:

```
Fatal error: Exit code 1 ()
Traceback (most recent call last):
  File "/export/tool_deps/_conda/envs/__multiqc@1.2/bin/multiqc", line 4, in 
    __import__('pkg_resources').run_script('multiqc==1.2', 'multiqc')
  File "/export/tool_deps/_conda/envs/__multiqc@1.2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3144, in 
    @_call_aside
  File "/export/tool_deps/_conda/envs/__multiqc@1.2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3128, in _call_aside
    f(*args, **kwargs)
  File "/export/tool_deps/_conda/envs/__multiqc@1.2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3157, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/export/tool_deps/_conda/envs/__multiqc@1.2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 666, in _build_master
    ws.require(__requires__)
  File "/export/tool_deps/_conda/envs/__multiqc@1.2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 984, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/export/tool_deps/_conda/envs/__multiqc@1.2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 870, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pytz' distribution was not found and is required by matplotlib
```

**Comment by yvanlebras** [comment]
Hi @vebaev Which MultiQC Galaxy tool are you using ? The Toolshed up-to-date version has been ameliorated and is hosted by IUC https://github.com/galaxyproject/tools-iuc/tree/master/tools/multiqc https://toolshed.g2.bx.psu.edu/view/iuc/multiqc/5746cb5cf08d .

**Comment by vebaev** [comment]
Yes I'm using this one 5746cb5cf08d from 2017-12-5, I have installed it an hour ago.

**Comment by yvanlebras** [comment]
OK, it was just to be sure of the version, thanks !
So I think the best way is to open an issue on the IUC repo https://github.com/galaxyproject/tools-iuc/tree/master/tools/multiqc as IUC is now maintening multiqc ! Is it ok for you ?

**Comment by vebaev** [comment]
You may close the issue, I found a strange thing, if I may ask:
I made a fresh new docker-galaxy instance installed the MultiQC and it worked. 
My working Galaxy is also v17 but updated from v16.
I copied /galaxy/tool_deps/_conda/envs$ cd __multiqc@1.2/ from the fresh instance to my working one and it worked.....Do you know what can be the issue? (I noticed similar behavior on 1-2 other tools);
(Nevertheless, when they installed on the working instance they are flagged green (installed ok))

**Comment by yvanlebras** [comment]
Hmmmm. Sorry I never got this kind of issues.... I will FW to Galaxy team just in case... and if I have a feedback, I will give you the answer here....

**Comment by yvanlebras** [comment]
A first answer from @bgruening: 

> She/he should check the conda channel configuration. Maybe this is an older one.

**Comment by yvanlebras** [comment]
and from @mvdbeek:

> Also make sure to run a recent version of conda

**Comment by yvanlebras** [comment]
and a comment from Marius:

> Also just copying the directories is never going to work, but maybe I misunderstood "I copied /galaxy/tool_deps/_conda/envs$ cd __multiqc@1.2/ from the fresh instance to my working one"

**Comment by vebaev** [comment]
Many thanks! I'm just running the latest version of Galaxy, but do not know how to check the conda channel configuration or version?
PS
Indeed I rsync-ed the folders between the two instance and the tool is working now :)

**Comment by mvdbeek** [comment]
It isn't a good idea in any case to assume copying environments is going to work, there are too many things that can go wrong. The channel configuration is listed in galaxy.ini.sample and it's always a good idea to use the newest one referenced in https://github.com/galaxyproject/galaxy/blob/dev/config/galaxy.ini.sample#L217. This can change over time.

**Comment by vebaev** [comment]
If it is in galaxy.ini it is possible unchanged as the original v17.09 file as I have changes only the settings for user login. I have upgraded from v16 to v17 in the described way by Bjorn by databases and installed tools and the galaxy.ini is almost unchanged. Anyway I'm see such behaviour after install of 2-3 tools like Mothur, Qiime, MultiQC for example.
