### ISSUE TITLE
It always used the last else section and fails reading the file

### ISSUE THREAD

**Issue by bimbam23** [EnginesOn/galaxy_tools#3]
This is very strange I selected fastqc (Raw Files) but its using the last Else statement:

`mkdir multiqc_WDir; mkdir multiqc_WDir/fastqc_0; cat /opt/galaxy/production/galaxy-dist/database/files/020/dataset_20859.dat > multiqc_WDir/fastqc_0/'FastQC on data 552: RawData'; mkdir multiqc_WDir/fastqc_1; cat /opt/galaxy/production/galaxy-dist/database/files/020/dataset_20857.dat > multiqc_WDir/fastqc_1/'FastQC on data 517: RawData'; mkdir multiqc_WDir/fastqc_2; cat /opt/galaxy/production/galaxy-dist/database/files/020/dataset_20855.dat > multiqc_WDir/fastqc_2/'FastQC on data 516: RawData'; multiqc multiqc_WDir;`

if I add an echo $repeat.software file;  somewhere to the code I print fastqc as expected.

**Comment by bimbam23** [comment]
It can be solved by converting the if condition to a string
#if $repeat.software == "fastqc"
TO
#if str($repeat.software) == "fastqc"

this needs to be done in every 'if statement

Cheers Jochen

**Comment by devengineson** [comment]
Hi Jochen,

Thank you for return in this issue and Moreover to propose a fix ;) we will
take you proposal into account for a new "release" of the tool.

Cheers,

Yvan

**Comment by cmonjeau** [comment]
Hi Jochen,

update was done in the main toolshed.

Cheers,
Cyril
